import { hashPassword } from './engines.js';
import type { IamDataSet, PermissionCode } from './types.js';

const permissions = [
  ['iam:read', 'Read IAM overview', 'API', 'iam', 'read'],
  ['iam:manage', 'Manage IAM settings', 'API', 'iam', 'manage'],
  ['user:read', 'Read users', 'API', 'user', 'read'],
  ['user:update', 'Update users', 'API', 'user', 'update'],
  ['role:read', 'Read roles', 'API', 'role', 'read'],
  ['role:update', 'Update roles', 'API', 'role', 'update'],
  ['menu:read', 'Read menus', 'MENU', 'menu', 'read'],
  ['policy:read', 'Read policies', 'API', 'policy', 'read'],
  ['policy:update', 'Update policies', 'API', 'policy', 'update'],
  ['session:read', 'Read online sessions', 'API', 'session', 'read'],
  ['session:revoke', 'Revoke sessions', 'API', 'session', 'revoke'],
  ['audit:read', 'Read audit logs', 'API', 'audit', 'read'],
  ['field:read', 'Read field permissions', 'FIELD', 'field', 'read'],
  ['data:read', 'Read data scopes', 'DATA', 'data', 'read'],
] as const;

export const createDemoIamData = (passwordSalt: string): IamDataSet => ({
  users: [
    {
      id: '1',
      username: 'admin',
      email: 'admin@tetap.local',
      passwordHash: hashPassword('password1', passwordSalt),
      status: 'ACTIVE',
      deptId: '100',
      tenantId: 'tenant-default',
      isSuperAdmin: true,
      roleCodes: ['super-admin'],
      tokenVersion: 1,
    },
    {
      id: '2',
      username: 'auditor',
      email: 'auditor@tetap.local',
      passwordHash: hashPassword('password1', passwordSalt),
      status: 'ACTIVE',
      deptId: '200',
      tenantId: 'tenant-default',
      isSuperAdmin: false,
      roleCodes: ['security-auditor'],
      tokenVersion: 1,
    },
  ],
  roles: [
    {
      id: '1',
      name: 'Super Admin',
      code: 'super-admin',
      description: 'Full IAM and platform administration.',
      permissionCodes: permissions.map(([code]) => code as PermissionCode),
      dataScope: { type: 'ALL' },
    },
    {
      id: '2',
      name: 'Security Auditor',
      code: 'security-auditor',
      description: 'Read-only security and audit visibility.',
      permissionCodes: [
        'iam:read',
        'user:read',
        'role:read',
        'policy:read',
        'session:read',
        'audit:read',
        'field:read',
        'data:read',
      ],
      dataScope: { type: 'DEPT_AND_CHILD', deptIds: ['200', '201'], deptField: 'deptId' },
    },
  ],
  permissions: permissions.map(([code, name, type, resource, action], index) => ({
    id: String(index + 1),
    code: code as PermissionCode,
    name,
    type,
    resource,
    action,
  })),
  menus: [
    {
      id: 'dashboard',
      name: 'Dashboard',
      path: '/',
      component: 'AdminDashboardPage',
      icon: 'LayoutDashboard',
      permissionCodes: [],
      order: 1,
    },
    {
      id: 'system',
      name: 'System Management',
      path: '/system',
      component: 'AdminSystemRedirectPage',
      icon: 'Settings',
      permissionCodes: [],
      order: 10,
    },
    {
      id: 'security',
      name: 'Security Center',
      path: '/security',
      component: 'AdminSecurityRedirectPage',
      icon: 'ShieldCheck',
      permissionCodes: [],
      order: 20,
    },
    {
      id: 'users',
      name: 'Users',
      path: '/system/user',
      component: 'AdminUsersPage',
      icon: 'Users',
      parentId: 'system',
      permissionCodes: ['user:read'],
      order: 11,
    },
    {
      id: 'roles',
      name: 'Roles',
      path: '/system/role',
      component: 'AdminRolesPage',
      icon: 'UserCog',
      parentId: 'system',
      permissionCodes: ['role:read'],
      order: 12,
    },
    {
      id: 'permissions',
      name: 'Permissions',
      path: '/system/permission',
      component: 'AdminPermissionsPage',
      icon: 'KeyRound',
      parentId: 'system',
      permissionCodes: ['iam:read'],
      order: 13,
    },
    {
      id: 'menus',
      name: 'Menus',
      path: '/system/menu',
      component: 'AdminMenusPage',
      icon: 'LayoutDashboard',
      parentId: 'system',
      permissionCodes: ['menu:read'],
      order: 14,
    },
    {
      id: 'fields',
      name: 'Field Permissions',
      path: '/security/fields',
      component: 'AdminFieldPermissionsPage',
      icon: 'KeyRound',
      parentId: 'security',
      permissionCodes: ['field:read'],
      order: 21,
    },
    {
      id: 'policies',
      name: 'Policies',
      path: '/security/policies',
      component: 'AdminPoliciesPage',
      icon: 'ShieldCheck',
      parentId: 'security',
      permissionCodes: ['policy:read'],
      order: 22,
    },
    {
      id: 'audit',
      name: 'Audit Logs',
      path: '/security/audit',
      component: 'AdminAuditPage',
      icon: 'LockKeyhole',
      parentId: 'security',
      permissionCodes: ['audit:read'],
      order: 23,
    },
    {
      id: 'sessions',
      name: 'Online Users',
      path: '/security/sessions',
      component: 'AdminSessionsPage',
      icon: 'MonitorCog',
      parentId: 'security',
      permissionCodes: ['session:read'],
      order: 24,
    },
  ],
  fieldPermissions: [
    {
      id: '1',
      roleCode: 'security-auditor',
      resource: 'user',
      fieldName: 'email',
      permissionType: 'MASK',
    },
    {
      id: '2',
      roleCode: 'security-auditor',
      resource: 'user',
      fieldName: 'phone',
      permissionType: 'MASK',
    },
    {
      id: '3',
      roleCode: 'security-auditor',
      resource: 'user',
      fieldName: 'idCard',
      permissionType: 'HIDE',
    },
  ],
  policies: [
    {
      id: '1',
      resource: 'session',
      action: 'revoke',
      effect: 'ALLOW',
      conditions: {
        any: [
          {
            source: 'user',
            path: 'isSuperAdmin',
            operator: 'eq',
            value: true,
          },
          {
            source: 'user',
            path: 'roleCodes',
            operator: 'contains',
            value: 'security-auditor',
          },
        ],
      },
    },
    {
      id: '2',
      resource: 'policy',
      action: 'update',
      effect: 'DENY',
      conditions: {
        all: [
          {
            source: 'environment',
            path: 'riskLevel',
            operator: 'eq',
            value: 'high',
          },
        ],
      },
    },
  ],
});
